# [sii] 代表生成的文件名是 sii.xml
[sii]
title = "上海创智学院 - 招生培养"
url = "https://www.sii.edu.cn/zsgz/list.htm"

# 1. 每一条新闻的容器 (对应之前的 $('ul.news_list li'))
entrySelector = "ul.news_list li"

# 2. 标题的选择器 (对应之前的 .news_wz .news_title)
titleSelector = ".news_wz .news_title"

# 3. 链接的选择器 (自动找 href 属性)
linkSelector = "a"
